version: "3.4"

services:
  deliveryboxschedule:
    image: deliveryboxschedule
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  db:
    container_name: dbSchedule
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres:
